version: "3.4"
  
services:
  categories-db:
    image: postgres:11-alpine
    container_name: categories-db
    ports:
      - "5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=categories_db
    volumes:
      - categories-data:/var/lib/postgresql/data

  categories-app:
    build: .
    container_name: categories-app
    environment:
      - DB_SERVER=categories-db
    ports:
      - 8080:8080
    links:
      - categories-db

volumes:
  categories-data: