version: "3.4"
  
services:
  db:
    container_name: categories_db
    image: postgres:11-alpine
    ports:
      - "5443:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=zombie_coder
      - POSTGRES_DB=categories_db
    tmpfs:
      - /var/lib/postgresql/data